# id = 677226551607033903
id = 1295798211096739974
hosts = ["localhost:6600"]

[format]
details = "$title"
state = "$artist"
timestamp = "both"
large_image = "notes"
small_image = "notes"
large_text = "$album"
small_text = "$album"
